### PR TITLE
QRReaderView: private funcs

### PR DESCRIPTION
**Pull request by evilbat831**
some bugs fixes + add some funs for authorisation blue effects metadataoutput etc...... hope you like it :) 
done by @evilbat831 
author: @krishpranav

### CODE REVIEW

**Comment by krishpranav** [comment]
hey @evilbat831  nice to see you here great work man!!

**Comment by krishpranav** [comment]
this will be helpful for me :)

**Comment by evilbat831** [comment]
THANKS!!

**Review by krishpranav — COMMENTED** [review]
great

**Pull request merged**
